apiVersion: apps/v1
kind:  StatefulSet
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  template:
    metadata:      
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
        app: elasticsearch
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms96m -Xmx96m
            - name: discovery.type
              value: single-node
          image: elasticsearch:7.10.1
          name: elasticsearch
          ports:
            - containerPort: 9200
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
            limits:
              memory: "400Mi"
              cpu: "250m"
          volumeMounts:
          - name: elasticsearch-data
            mountPath: /usr/share/elasticsearch/data
      restartPolicy: Always
  volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
           - ReadWriteOnce
          storageClassName: "nfs-client"
          resources:
           requests:
              storage: 2Gi
---

apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
  selector:
    io.kompose.service: elasticsearch
status:
  loadBalancer: {}