apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: default
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:7.10.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: "256Mi"
          limits:
            cpu: 200m
            memory: "350Mi"
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch.default.svc.cluster.local:9200
          - name: ELASTICSEARCH_HOSTS
            value: http://elasticsearch.default.svc.cluster.local:9200
            
        ports:
        - containerPort: 5601
        
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: default
  labels:
    app: kibana
spec:
  ports:
  - port: 80
    targetPort: 5601
  selector:
    app: kibana
  type: LoadBalancer